api_platform:
    title: 'Trogon Studios website API'
    description: 'API providing access to the content of Trogon Studios website'
    version: '1.1.0'
    show_webby: false
    metadata_backward_compatibility_layer: false
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_client_items_per_page: true
