api_platform:
    title: 'Trogon Studios website API'
    description: 'API providing access to the content of Trogon Studios website'
    version: '1.1.0'
    show_webby: false
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
    formats:
        jsonld: ['application/ld+json']
    defaults:
        pagination_client_items_per_page: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true

