# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            bitbucket_api.client:
                http_version: 1.1
                base_uri: https://api.bitbucket.org/
                verify_peer: false
            bitbucket_oauth.client:
                base_uri: https://bitbucket.org/site/oauth2/
                auth_basic: 'mxnvmeayDbKeqcBcRM:a6FCepBfAtV6WDDCtvcsCDp4vmYAqdYj'
                verify_peer: false
            github_api.client:
                base_uri: https://api.github.com/
                # this mean if authentication will be removed in 2021
                auth_basic: 'a6de26f9bd5efaa78116:713486ebf104bbb997a4cb9b861bf534b7f403ea'
                verify_peer: false
            github_oauth.client:
                base_uri: https://github.com/login/oauth/
                verify_peer: false
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
