services:
###> doctrine/doctrine-bundle ###
  database-pgsql:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data-pgsql:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  database-mysql:
    image: mysql:${MYSQL_VERSION:-8}-debian
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-app}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - db-data-mysql:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  webserver:
    image: chialab/php-dev:${PHP_VERSION:-8.3}-apache
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    volumes:
      - ./docker/user-php.ini:/usr/local/etc/php/conf.d/docker-user.ini:r
      - .:/var/www/html:rw

volumes:
###> doctrine/doctrine-bundle ###
  db-data-mysql:
  db-data-pgsql:
###< doctrine/doctrine-bundle ###
