services:
###> doctrine/doctrine-bundle ###
  database-pgsql:
    ports:
      - "5432"

  database-mysql:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

  webserver:
    ports:
      - "81:80"

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
